# Script for creating and encoding a blank font covering
# latin-1 + latin-extended-A
# Johannes 'kontur' Neumeier, 2015
#

from robofab.world import CurrentFont
from robofab.world import CurrentGlyph
from robofab.interface.all.dialogs import *
glyphs = {
	#latin-1
	'SP': ['0020', 'space', ''],
	'!': ['0021', 'exclam', ''],
	'"': ['0022', 'quotedbl', ''],
	'#': ['0023', 'numbersign', ''],
	'$': ['0024', 'dollar', ''],
	'%': ['0025', 'percent', ''],
	'&': ['0026', 'ampersand', ''],
	'\'': ['0027', 'quotesingle', ''],
	'(': ['0028', 'parenleft', ''],
	')': ['0029', 'parenright', ''],
	'*': ['002A', 'asterisk', ''],
	'+': ['002B', 'plus', ''],
	',': ['002C', 'comma', ''],
	'-': ['002D', 'hyphen', ''],
	'.': ['002E', 'period', ''],
	'/': ['002F', 'slash', ''],
	'0': ['0030', 'zero', ''],
	'1': ['0031', 'one', ''],
	'2': ['0032', 'two', ''],
	'3': ['0033', 'three', ''],
	'4': ['0034', 'four', ''],
	'5': ['0035', 'five', ''],
	'6': ['0036', 'six', ''],
	'7': ['0037', 'seven', ''],
	'8': ['0038', 'eight', ''],
	'9': ['0039', 'nine', ''],
	':': ['003A', 'colon', ''],
	';': ['003B', 'semicolon', ''],
	'<': ['003C', 'less', ''],
	'=': ['003D', 'equal', ''],
	'>': ['003E', 'greater', ''],
	'?': ['003F', 'question', ''],
	'@': ['0040', 'at', ''],
	'A': ['0041', 'A', ''],
	'B': ['0042', 'B', ''],
	'C': ['0043', 'C', ''],
	'D': ['0044', 'D', ''],
	'E': ['0045', 'E', ''],
	'F': ['0046', 'F', ''],
	'G': ['0047', 'G', ''],
	'H': ['0048', 'H', ''],
	'I': ['0049', 'I', ''],
	'J': ['004A', 'J', ''],
	'K': ['004B', 'K', ''],
	'L': ['004C', 'L', ''],
	'M': ['004D', 'M', ''],
	'N': ['004E', 'N', ''],
	'O': ['004F', 'O', ''],
	'P': ['0050', 'P', ''],
	'Q': ['0051', 'Q', ''],
	'R': ['0052', 'R', ''],
	'S': ['0053', 'S', ''],
	'T': ['0054', 'T', ''],
	'U': ['0055', 'U', ''],
	'V': ['0056', 'V', ''],
	'W': ['0057', 'W', ''],
	'X': ['0058', 'X', ''],
	'Y': ['0059', 'Y', ''],
	'Z': ['005A', 'Z', ''],
	'[': ['005B', 'bracketleft', ''],
	'\\': ['005C', 'backslash', ''],
	']': ['005D', 'bracketright', ''],
	'^': ['005E', 'asciicircum', ''],
	'_': ['005F', 'underscore', ''],
	'`': ['0060', 'grave', ''],
	'a': ['0061', 'a', ''],
	'b': ['0062', 'b', ''],
	'c': ['0063', 'c', ''],
	'd': ['0064', 'd', ''],
	'e': ['0065', 'e', ''],
	'f': ['0066', 'f', ''],
	'g': ['0067', 'g', ''],
	'h': ['0068', 'h', ''],
	'i': ['0069', 'i', ''],
	'j': ['006A', 'j', ''],
	'k': ['006B', 'k', ''],
	'l': ['006C', 'l', ''],
	'm': ['006D', 'm', ''],
	'n': ['006E', 'n', ''],
	'o': ['006F', 'o', ''],
	'p': ['0070', 'p', ''],
	'q': ['0071', 'q', ''],
	'r': ['0072', 'r', ''],
	's': ['0073', 's', ''],
	't': ['0074', 't', ''],
	'u': ['0075', 'u', ''],
	'v': ['0076', 'v', ''],
	'w': ['0077', 'w', ''],
	'x': ['0078', 'x', ''],
	'y': ['0079', 'y', ''],
	'z': ['007A', 'z', ''],
	'{': ['007B', 'braceleft', ''],
	'|': ['007C', 'bar', ''],
	'}': ['007D', 'braceright', ''],
	'~': ['007E', 'asciitilde', ''],
	#'NBSP': ['00A0', '---', ''],
	'¡': ['00A1', 'exclamdown', ''],
	'¢': ['00A2', 'cent', ''],
	'£': ['00A3', 'sterling', ''],
	'¤': ['00A4', 'currency', ''],
	'¥': ['00A5', 'yen', ''],
	'¦': ['00A6', 'brokenbar', ''],
	'§': ['00A7', 'section', ''],
	'¨': ['00A8', 'dieresis', ''],
	'©': ['00A9', 'copyright', ''],
	'ª': ['00AA', 'ordfeminine', ''],
	'«': ['00AB', 'guillemotleft', ''],
	'¬': ['00AC', 'logicalnot', ''],
	#'SHY': ['00AD', 'uni00AD', ''],
	'®': ['00AE', 'registered', ''],
	'¯': ['00AF', 'macron', ''],
	'°': ['00B0', 'degree', ''],
	'±': ['00B1', 'plusminus', ''],
	'²': ['00B2', 'twosuperior', ''],
	'³': ['00B3', 'threesuperior', ''],
	'´': ['00B4', 'acute', ''],
	'µ': ['00B5', 'mu', ''],
	'¶': ['00B6', 'paragraph', ''],
	'·': ['00B7', 'periodcentered', ''],
	'¸': ['00B8', 'cedilla', ''],
	'¹': ['00B9', 'onesuperior', ''],
	'º': ['00BA', 'ordmasculine', ''],
	'»': ['00BB', 'guillemotright', ''],
	'¼': ['00BC', 'onequarter', ''],
	'½': ['00BD', 'onehalf', ''],
	'¾': ['00BE', 'threequarters', ''],
	'¿': ['00BF', 'questiondown', ''],
	'À': ['00C0', 'Agrave', ''],
	'Á': ['00C1', 'Aacute', ''],
	'Â': ['00C2', 'Acircumflex', ''],
	'Ã': ['00C3', 'Atilde', ''],
	'Ä': ['00C4', 'Adieresis', ''],
	'Å': ['00C5', 'Aring', ''],
	'Æ': ['00C6', 'AE', ''],
	'Ç': ['00C7', 'Ccedilla', ''],
	'È': ['00C8', 'Egrave', ''],
	'É': ['00C9', 'Eacute', ''],
	'Ê': ['00CA', 'Ecircumflex', ''],
	'Ë': ['00CB', 'Edieresis', ''],
	'Ì': ['00CC', 'Igrave', ''],
	'Í': ['00CD', 'Iacute', ''],
	'Î': ['00CE', 'Icircumflex', ''],
	'Ï': ['00CF', 'Idieresis', ''],
	'Ð': ['00D0', 'Eth', ''],
	'Ñ': ['00D1', 'Ntilde', ''],
	'Ò': ['00D2', 'Ograve', ''],
	'Ó': ['00D3', 'Oacute', ''],
	'Ô': ['00D4', 'Ocircumflex', ''],
	'Õ': ['00D5', 'Otilde', ''],
	'Ö': ['00D6', 'Odieresis', ''],
	'×': ['00D7', 'multiply', ''],
	'Ø': ['00D8', 'Oslash', ''],
	'Ù': ['00D9', 'Ugrave', ''],
	'Ú': ['00DA', 'Uacute', ''],
	'Û': ['00DB', 'Ucircumflex', ''],
	'Ü': ['00DC', 'Udieresis', ''],
	'Ý': ['00DD', 'Yacute', ''],
	'Þ': ['00DE', 'Thorn', ''],
	'ß': ['00DF', 'germandbls', ''],
	'à': ['00E0', 'agrave', ''],
	'á': ['00E1', 'aacute', ''],
	'â': ['00E2', 'acircumflex', ''],
	'ã': ['00E3', 'atilde', ''],
	'ä': ['00E4', 'adieresis', ''],
	'å': ['00E5', 'aring', ''],
	'æ': ['00E6', 'ae', ''],
	'ç': ['00E7', 'ccedilla', ''],
	'è': ['00E8', 'egrave', ''],
	'é': ['00E9', 'eacute', ''],
	'ê': ['00EA', 'ecircumflex', ''],
	'ë': ['00EB', 'edieresis', ''],
	'ì': ['00EC', 'igrave', ''],
	'í': ['00ED', 'iacute', ''],
	'î': ['00EE', 'icircumflex', ''],
	'ï': ['00EF', 'idieresis', ''],
	'ð': ['00F0', 'eth', ''],
	'ñ': ['00F1', 'ntilde', ''],
	'ò': ['00F2', 'ograve', ''],
	'ó': ['00F3', 'oacute', ''],
	'ô': ['00F4', 'ocircumflex', ''],
	'õ': ['00F5', 'otilde', ''],
	'ö': ['00F6', 'odieresis', ''],
	'÷': ['00F7', 'divide', ''],
	'ø': ['00F8', 'oslash', ''],
	'ù': ['00F9', 'ugrave', ''],
	'ú': ['00FA', 'uacute', ''],
	'û': ['00FB', 'ucircumflex', ''],
	'ü': ['00FC', 'udieresis', ''],
	'ý': ['00FD', 'yacute', ''],
	'þ': ['00FE', 'thorn', ''],
	'ÿ': ['00FF', 'ydieresis', ''],

	# latin extended-a
	'Ā': ['0100', 'Amacron', 'Latin Capital Letter A with macron'],
	'ā': ['0101', 'amacron', 'Latin Small Letter A with macron'],
	'Ă': ['0102', 'Abreve', 'Latin Capital Letter A with breve'],
	'ă': ['0103', 'abreve', 'Latin Small Letter A with breve'],
	'Ą': ['0104', 'Aogonek', 'Latin Capital Letter A with ogonek'],
	'ą': ['0105', 'aogonek', 'Latin Small Letter A with ogonek'],
	'Ć': ['0106', 'Cacute', 'Latin Capital Letter C with acute'],
	'ć': ['0107', 'cacute', 'Latin Small Letter C with acute'],
	'Ĉ': ['0108', 'Ccircumflex', 'Latin Capital Letter C with circumflex'],
	'ĉ': ['0109', 'ccircumflex', 'Latin Small Letter C with circumflex'],
	'Ċ': ['010A', 'Cdotaccent', 'Latin Capital Letter C with dot above'],
	'ċ': ['010B', 'cdotaccent', 'Latin Small Letter C with dot above'],
	'Č': ['010C', 'Ccaron', 'Latin Capital Letter C with caron'],
	'č': ['010D', 'ccaron', 'Latin Small Letter C with caron'],
	'Ď': ['010E', 'Dcaron', 'Latin Capital Letter D with caron'],
	'ď': ['010F', 'dcaron', 'Latin Small Letter D with caron'],
	'Đ': ['0110', 'Dcroat', 'Latin Capital Letter D with stroke'],
	'đ': ['0111', 'dcroat', 'Latin Small Letter D with stroke'],
	'Ē': ['0112', 'Emacron', 'Latin Capital Letter E with macron'],
	'ē': ['0113', 'emacron', 'Latin Small Letter E with macron'],
	'Ĕ': ['0114', 'Ebreve', 'Latin Capital Letter E with breve'],
	'ĕ': ['0115', 'ebreve', 'Latin Small Letter E with breve'],
	'Ė': ['0116', 'Edotaccent', 'Latin Capital Letter E with dot above'],
	'ė': ['0117', 'edotaccent', 'Latin Small Letter E with dot above'],
	'Ę': ['0118', 'Eogonek', 'Latin Capital Letter E with ogonek'],
	'ę': ['0119', 'eogonek', 'Latin Small Letter E with ogonek'],
	'Ě': ['011A', 'Ecaron', 'Latin Capital Letter E with caron'],
	'ě': ['011B', 'ecaron', 'Latin Small Letter E with caron'],
	'Ĝ': ['011C', 'Gcircumflex', 'Latin Capital Letter G with circumflex'],
	'ĝ': ['011D', 'gcircumflex', 'Latin Small Letter G with circumflex'],
	'Ğ': ['011E', 'Gbreve', 'Latin Capital Letter G with breve'],
	'ğ': ['011F', 'gbreve', 'Latin Small Letter G with breve'],
	'Ġ': ['0120', 'Gdotaccent', 'Latin Capital Letter G with dot above'],
	'ġ': ['0121', 'gdotaccent', 'Latin Small Letter G with dot above'],
	'Ģ': ['0122', 'Gcedilla', 'Latin Capital Letter G with cedilla'],
	'ģ': ['0123', 'gcedilla', 'Latin Small Letter G with cedilla'],
	'Ĥ': ['0124', 'Hcircumflex', 'Latin Capital Letter H with circumflex'],
	'ĥ': ['0125', 'hcircumflex', 'Latin Small Letter H with circumflex'],
	'Ħ': ['0126', 'Hbar', 'Latin Capital Letter H with stroke'],
	'ħ': ['0127', 'hbar', 'Latin Small Letter H with stroke'],
	'Ĩ': ['0128', 'Itilde', 'Latin Capital Letter I with tilde'],
	'ĩ': ['0129', 'itilde', 'Latin Small Letter I with tilde'],
	'Ī': ['012A', 'Imacron', 'Latin Capital Letter I with macron'],
	'ī': ['012B', 'imacron', 'Latin Small Letter I with macron'],
	'Ĭ': ['012C', 'Ibreve', 'Latin Capital Letter I with breve'],
	'ĭ': ['012D', 'ibreve', 'Latin Small Letter I with breve'],
	'Į': ['012E', 'Iogonek', 'Latin Capital Letter I with ogonek'],
	'į': ['012F', 'iogonek', 'Latin Small Letter I with ogonek'],
	'İ': ['0130', 'Idotaccent', 'Latin Capital Letter I with dot above'],
	'ı': ['0131', 'dotlessi', 'Latin Small Letter dotless I'],
	'Ĳ': ['0132', 'IJ', 'Latin Capital Ligature IJ'],
	'ĳ': ['0133', 'ij', 'Latin Small Ligature IJ'],
	'Ĵ': ['0134', 'Jcircumflex', 'Latin Capital Letter J with circumflex'],
	'ĵ': ['0135', 'jcircumflex', 'Latin Small Letter J with circumflex'],
	'Ķ': ['0136', 'Kcedilla', 'Latin Capital Letter K with cedilla'],
	'ķ': ['0137', 'kcedilla', 'Latin Small Letter K with cedilla'],
	'ĸ': ['0138', 'kgreenlandic', 'Latin Small Letter Kra'],
	'Ĺ': ['0139', 'Lacute', 'Latin Capital Letter L with acute'],
	'ĺ': ['013A', 'lacute', 'Latin Small Letter L with acute'],
	'Ļ': ['013B', 'Lcedilla', 'Latin Capital Letter L with cedilla'],
	'ļ': ['013C', 'lcedilla', 'Latin Small Letter L with cedilla'],
	'Ľ': ['013D', 'Lcaron', 'Latin Capital Letter L with caron'],
	'ľ': ['013E', 'lcaron', 'Latin Small Letter L with caron'],
	'Ŀ': ['013F', 'Ldot', 'Latin Capital Letter L with middle dot'],
	'ŀ': ['0140', 'ldot', 'Latin Small Letter L with middle dot'],
	'Ł': ['0141', 'Lslash', 'Latin Capital Letter L with stroke'],
	'ł': ['0142', 'lslash', 'Latin Small Letter L with stroke'],
	'Ń': ['0143', 'Nacute', 'Latin Capital Letter N with acute'],
	'ń': ['0144', 'nacute', 'Latin Small Letter N with acute'],
	'Ņ': ['0145', 'Ncedilla', 'Latin Capital Letter N with cedilla'],
	'ņ': ['0146', 'ncedilla', 'Latin Small Letter N with cedilla'],
	'Ň': ['0147', 'Ncaron', 'Latin Capital Letter N with caron'],
	'ň': ['0148', 'ncaron', 'Latin Small Letter N with caron'],
	'ŉ': ['0149', 'napostrophe', 'Latin Small Letter N preceded by apostrophe'],
	'Ŋ': ['014A', 'Eng', 'Latin Capital Letter Eng'],
	'ŋ': ['014B', 'eng', 'Latin Small Letter Eng'],
	'Ō': ['014C', 'Omacron', 'Latin Capital Letter O with macron'],
	'ō': ['014D', 'omacron', 'Latin Small Letter O with macron'],
	'Ŏ': ['014E', 'Obreve', 'Latin Capital Letter O with breve'],
	'ŏ': ['014F', 'obreve', 'Latin Small Letter O with breve'],
	'Ő': ['0150', 'Ohungarumlaut', 'Latin Capital Letter O with double acute'],
	'ő': ['0151', 'ohungarumlaut', 'Latin Small Letter O with double acute'],
	'Œ': ['0152', 'OE', 'Latin Capital Ligature OE'],
	'œ': ['0153', 'oe', 'Latin Small Ligature OE'],
	'Ŕ': ['0154', 'Racute', 'Latin Capital Letter R with acute'],
	'ŕ': ['0155', 'racute', 'Latin Small Letter R with acute'],
	'Ŗ': ['0156', 'Rcedilla', 'Latin Capital Letter R with cedilla'],
	'ŗ': ['0157', 'rcedilla', 'Latin Small Letter R with cedilla'],
	'Ř': ['0158', 'Rcaron', 'Latin Capital Letter R with caron'],
	'ř': ['0159', 'rcaron', 'Latin Small Letter R with caron'],
	'Ś': ['015A', 'Sacute', 'Latin Capital Letter S with acute'],
	'ś': ['015B', 'sacute', 'Latin Small Letter S with acute'],
	'Ŝ': ['015C', 'Scircumflex', 'Latin Capital Letter S with circumflex'],
	'ŝ': ['015D', 'scircumflex', 'Latin Small Letter S with circumflex'],
	'Ş': ['015E', 'Scedilla', 'Latin Capital Letter S with cedilla'],
	'ş': ['015F', 'scedilla', 'Latin Small Letter S with cedilla'],
	'Š': ['0160', 'Scaron', 'Latin Capital Letter S with caron'],
	'š': ['0161', 'scaron', 'Latin Small Letter S with caron'],
	'Ţ': ['0162', 'Tcedilla', 'Latin Capital Letter T with cedilla'],
	'ţ': ['0163', 'tcedilla', 'Latin Small Letter T with cedilla'],
	'Ť': ['0164', 'Tcaron', 'Latin Capital Letter T with caron'],
	'ť': ['0165', 'tcaron', 'Latin Small Letter T with caron'],
	'Ŧ': ['0166', 'Tbar', 'Latin Capital Letter T with stroke'],
	'ŧ': ['0167', 'tbar', 'Latin Small Letter T with stroke'],
	'Ũ': ['0168', 'Utilde', 'Latin Capital Letter U with tilde'],
	'ũ': ['0169', 'utilde', 'Latin Small Letter U with tilde'],
	'Ū': ['016A', 'Umacron', 'Latin Capital Letter U with macron'],
	'ū': ['016B', 'umacron', 'Latin Small Letter U with macron'],
	'Ŭ': ['016C', 'Ubreve', 'Latin Capital Letter U with breve'],
	'ŭ': ['016D', 'ubreve', 'Latin Small Letter U with breve'],
	'Ů': ['016E', 'Uring', 'Latin Capital Letter U with ring above'],
	'ů': ['016F', 'uring', 'Latin Small Letter U with ring above'],
	'Ű': ['0170', 'Uhungarumlaut', 'Latin Capital Letter U with double acute'],
	'ű': ['0171', 'uhungarumlaut', 'Latin Small Letter U with double acute'],
	'Ų': ['0172', 'Uogonek', 'Latin Capital Letter U with ogonek'],
	'ų': ['0173', 'uogonek', 'Latin Small Letter U with ogonek'],
	'Ŵ': ['0174', 'Wcircumflex', 'Latin Capital Letter W with circumflex'],
	'ŵ': ['0175', 'wcircumflex', 'Latin Small Letter W with circumflex'],
	'Ŷ': ['0176', 'Ycircumflex', 'Latin Capital Letter Y with circumflex'],
	'ŷ': ['0177', 'ycircumflex', 'Latin Small Letter Y with circumflex'],
	'Ÿ': ['0178', 'Ydieresis', 'Latin Capital Letter Y with diaeresis'],
	'Ź': ['0179', 'Zacute', 'Latin Capital Letter Z with acute'],
	'ź': ['017A', 'zacute', 'Latin Small Letter Z with acute'],
	'Ż': ['017B', 'Zdotaccent', 'Latin Capital Letter Z with dot above'],
	'ż': ['017C', 'zdotaccent', 'Latin Small Letter Z with dot above'],
	'Ž': ['017D', 'Zcaron', 'Latin Capital Letter Z with caron'],
	'ž': ['017E', 'zcaron', 'Latin Small Letter Z with caron'],
	'ſ': ['017F', 'longs', 'Latin Small Letter long S'],

	#personal additions

	#accents by themselves
	'grave': ['', 'grave', ''],
	'acute': ['0301', 'acute', ''],
	'dieresis': ['', 'dieresis', ''],
	'macron': ['', 'macron', ''],
	'acute': ['', 'acute', ''],
	'circumflex': ['', 'circumflex', ''],
	'ogonek': ['', 'ogonek', ''],
	'cedilla': ['', 'cedilla', ''],
	'caron': ['', 'caron', ''],
	'hungarumlaut': ['', 'hungarumlaut', ''],
	'ring': ['', 'ring', ''],
	'dotaccent': ['', 'dotaccent', ''],
	'breve': ['', 'breve', ''],

	#additional diacritics
	'Wgrave': ['', 'Wgrave', ''],
	'wgrave': ['', 'wgrave', ''],
	'Wacute': ['', 'Wacute', ''],
	'wacute': ['', 'wacute', ''],
	'Wdieresis': ['', 'Wdieresis', ''],
	'wdieresis': ['', 'wdieresis', ''],
	'Capitalß': ['1E9E', 'uni1E9E', 'LATIN CAPITAL LETTER SHARP S'],
	'dotlessj': ['0237', 'uni0237', ''],
	'ijacute': ['', '', ''], #TODO unicode?


	#addition punctuation
	'quotesinglbase': ['201A', 'quotesinglbase', ''],
	'quotedblbase': ['', 'quotedblbase', ''],
	'quoteleft': ['', 'quoteleft', ''],
	'quoteright': ['', 'quoteright', ''],
	'quotedblleft': ['201C', 'quotedblleft', ''],
	'quotedblright': ['', 'quotedblright', ''],
	'bullet': ['', 'bullet', ''],
	'endash': ['', 'endash', ''],
	'emdash': ['', 'emdash', ''],
	'tilde': ['', 'tilde', ''],
	'guilsinglleft': ['', 'guilsinglleft', ''],
	'guilsinglright': ['', 'guilsinglright', ''],
	'perthousand': ['', 'perthousand', ''],
	'ellipsis': ['', 'ellipsis', ''],

	#mathematical symbols
	'minus': ['', 'minus', ''],
	'fraction': ['', 'fraction', ''],
	'approxequal': ['', 'approxequal', ''],
	'notequal': ['', 'notequal', ''],
	'lessqual': ['', 'lessequal', ''],
	'greaterqual': ['', 'greaterequal', ''],
	'infinity': ['', 'infinity', ''],
	'integral': ['', 'integral', ''],
	'radical': ['', 'radical', ''],

	#additional currencies
	'Euro': ['', 'Euro', ''],
	'florin': ['', 'florin', ''],

	#misc
	'dagger': ['2020', 'dagger', ''],
	'daggerdbl': ['2021', 'daggerdbl', ''],
	'trademark': ['', 'trademark', ''],
	'estimated': ['', 'estimated', ''],

	#common ligatures
	'f_f': ['', 'f_f', ''],
	'fi': ['', 'fi', ''],
	'fl': ['', 'fl', ''],
	'f_f_i': ['', 'f_f_i', ''],
	'f_f_l': ['', 'f_f_l', ''],
	'longs_t': ['', 'longs_t', ''],
	'c_h': ['', 'c_h', ''],
	'c_k': ['', 'c_k', ''],
	's_t': ['', 's_t', ''],
	'c_t': ['', 'c_t', ''],
}


print ""
print "Starting latin-extended-A glyph placeholder generation"

font = CurrentFont()

print font

for glyph in glyphs:

	gUnicode = glyphs[glyph][0]
	gName = glyphs[glyph][1]
		
	if gName is not "":	
		if gName in font:
			font[gName].mark = 250
			print gName + " already in font"
		else:
			new = font.newGlyph(gName, False)
			print new
			# font[gName].unicode = gUnicode
			font[gName].mark = 200
font.update()

print "Script done"
print ""
